version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Syncs current directory with /app in the container
    ports:
      - "5001:5000" # Map container port 5000 to host port 5001
    environment:
      FLASK_APP: backend/app.py
      FLASK_RUN_HOST: 0.0.0.0 # Ensures Flask binds to 0.0.0.0
    env_file:
      - .env # Load environment variables from .env file
    command: flask run --host=0.0.0.0 # Run the Flask app
